"""Send a daily report immediately — standalone, no asyncio conflicts."""
import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ".")

from dotenv import dotenv_values
from ib_insync import IB

env = dotenv_values(".env")

# Connect to IB
ib = IB()
ib.connect("127.0.0.1", int(env.get("IB_PORT", "4002")), clientId=98)
ib.sleep(2)

# Gather data
nlv = cash = upnl = rpnl = 0.0
for av in ib.accountValues():
    if av.currency == "BASE":
        if av.tag == "NetLiquidation": nlv = float(av.value)
        if av.tag == "TotalCashBalance": cash = float(av.value)
        if av.tag == "UnrealizedPnL": upnl = float(av.value)
        if av.tag == "RealizedPnL": rpnl = float(av.value)

positions = ib.portfolio()
fills = ib.fills()
start_capital = 1_000_000.0
total_pnl = nlv - start_capital
pnl_pct = (total_pnl / start_capital) * 100

# Build HTML
D = "$"
now = datetime.now().strftime("%Y-%m-%d %H:%M")
pnl_color = "#2ecc71" if total_pnl >= 0 else "#e74c3c"

pos_rows = ""
for item in positions:
    sym = item.contract.symbol
    qty = int(item.position)
    avg = item.averageCost
    mkt = item.marketPrice
    val = item.marketValue
    pnl = item.unrealizedPNL
    c = "#2ecc71" if pnl >= 0 else "#e74c3c"
    typ = "LONG" if qty > 0 else "SHORT"
    pos_rows += f"""<tr>
        <td style="padding:6px;font-weight:bold">{sym}</td>
        <td style="padding:6px;text-align:right">{qty}</td>
        <td style="padding:6px;text-align:right">{D}{avg:,.2f}</td>
        <td style="padding:6px;text-align:right">{D}{mkt:,.2f}</td>
        <td style="padding:6px;text-align:right">{D}{val:,.0f}</td>
        <td style="padding:6px;text-align:right;color:{c}">{D}{pnl:+,.0f}</td>
        <td style="padding:6px">{typ}</td>
    </tr>"""

if not pos_rows:
    pos_rows = '<tr><td colspan="7" style="padding:10px;color:#95a5a6">No open positions</td></tr>'

html = f"""<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden">

<tr><td style="background:#2c3e50;padding:20px 30px;color:#fff">
<h1 style="margin:0;font-size:20px">IB Trading Agent — Daily Report</h1>
<p style="margin:4px 0 0;font-size:13px;color:#bdc3c7">{now}</p>
</td></tr>

<tr><td style="padding:20px 30px">
<h2 style="font-size:16px;color:#2c3e50;border-bottom:2px solid #ecf0f1;padding-bottom:6px">Account Summary</h2>
<table width="100%" style="font-size:14px">
<tr><td style="color:#7f8c8d;padding:4px 0">Starting Capital</td><td style="text-align:right">{D}1,000,000</td></tr>
<tr style="background:#f9f9f9"><td style="color:#7f8c8d;padding:4px 0">Net Liquidation</td><td style="text-align:right;font-weight:bold">{D}{nlv:,.0f}</td></tr>
<tr><td style="color:#7f8c8d;padding:4px 0">Cash Balance</td><td style="text-align:right">{D}{cash:,.0f}</td></tr>
<tr style="background:#f9f9f9"><td style="color:#7f8c8d;padding:4px 0">Unrealized P&L</td><td style="text-align:right;color:{pnl_color}">{D}{upnl:+,.0f}</td></tr>
<tr><td style="color:#7f8c8d;padding:4px 0">Realized P&L</td><td style="text-align:right;color:{pnl_color}">{D}{rpnl:+,.0f}</td></tr>
<tr style="background:#f9f9f9"><td style="color:#7f8c8d;padding:4px 0;font-weight:bold">Total P&L</td><td style="text-align:right;font-weight:bold;color:{pnl_color}">{D}{total_pnl:+,.0f} ({pnl_pct:+.2f}%)</td></tr>
</table>
</td></tr>

<tr><td style="padding:20px 30px">
<h2 style="font-size:16px;color:#2c3e50;border-bottom:2px solid #ecf0f1;padding-bottom:6px">Open Positions ({len(positions)})</h2>
<table width="100%" style="font-size:13px;border-collapse:collapse">
<tr style="background:#2c3e50;color:#fff"><th style="padding:8px;text-align:left">Symbol</th><th style="padding:8px;text-align:right">Qty</th><th style="padding:8px;text-align:right">Avg Cost</th><th style="padding:8px;text-align:right">Mkt Price</th><th style="padding:8px;text-align:right">Value</th><th style="padding:8px;text-align:right">P&L</th><th style="padding:8px">Type</th></tr>
{pos_rows}
</table>
</td></tr>

<tr><td style="padding:20px 30px">
<h2 style="font-size:16px;color:#2c3e50;border-bottom:2px solid #ecf0f1;padding-bottom:6px">Activity</h2>
<p style="font-size:14px">Fills today: <strong>{len(fills)}</strong></p>
</td></tr>

<tr><td style="background:#ecf0f1;padding:12px 30px;text-align:center">
<p style="margin:0;font-size:11px;color:#95a5a6">Generated by IB Trading Agent at {now}</p>
</td></tr>

</table></td></tr></table></body></html>"""

# Send email
msg = MIMEMultipart("alternative")
msg["Subject"] = f"IB Trading Agent — Daily Report {datetime.now().strftime('%Y-%m-%d')}"
msg["From"] = env.get("EMAIL_SMTP_USER", "")
msg["To"] = env.get("EMAIL_ADDRESS", "")
msg.attach(MIMEText(html, "html"))

try:
    with smtplib.SMTP(env["EMAIL_SMTP_HOST"], int(env.get("EMAIL_SMTP_PORT", "587"))) as server:
        server.starttls()
        server.login(env["EMAIL_SMTP_USER"], env["EMAIL_SMTP_PASSWORD"])
        server.sendmail(env["EMAIL_SMTP_USER"], env["EMAIL_ADDRESS"], msg.as_string())
    print("REPORT SENT SUCCESSFULLY")
except Exception as e:
    print(f"SEND FAILED: {e}")
    # Save locally
    os.makedirs("data/reports", exist_ok=True)
    fname = f"data/reports/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    with open(fname, "w") as f:
        f.write(html)
    print(f"Saved locally: {fname}")

ib.disconnect()
