"""Domain object dataclasses for the IB Trading Agent.

All domain objects used across the agent: trade signals, approved trades,
trade records, portfolio snapshots, discrepancies, analysis state, and
agent operational state.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional


@dataclass
class TradeSignal:
    """A trading signal generated by the StrategyEngine."""

    symbol: str
    direction: str  # "BUY" or "SELL"
    strategy: str  # "momentum", "mean_reversion", "trend_following"
    confidence: float  # 0.0 to 1.0
    price: float
    volume: float
    indicators: Dict[str, float]  # RSI, MACD, BB values, etc.
    polymarket_sentiment: float
    timestamp: datetime


@dataclass
class ApprovedTrade:
    """A trade that has passed all risk checks and is ready for execution."""

    signal: TradeSignal
    quantity: int
    stop_loss_price: float
    max_position_value: float


@dataclass
class TradeRecord:
    """A persisted record of an executed trade."""

    symbol: str
    direction: str
    entry_price: float
    quantity: int
    stop_loss_price: float
    strategy: str
    signal_confidence: float
    polymarket_sentiment: float
    entry_time: datetime
    exit_price: Optional[float] = None
    exit_time: Optional[datetime] = None
    realized_pnl: Optional[float] = None
    status: str = "OPEN"


@dataclass
class PortfolioSnapshot:
    """A point-in-time snapshot of the portfolio state."""

    total_value: float
    cash_balance: float
    positions_value: float
    daily_pnl: float
    total_pnl: float
    total_pnl_pct: float
    num_open_positions: int
    hard_stop_active: bool
    snapshot_time: datetime


@dataclass
class Discrepancy:
    """A discrepancy found during state reconciliation with IB."""

    field: str
    local_value: Any
    ib_value: Any
    resolution: str  # "updated_to_ib"


@dataclass
class AnalysisState:
    """Persisted analysis state: watchlist, signals, indicators, and sentiment."""

    watchlist: List[str]
    active_signals: List[TradeSignal]
    indicator_values: Dict[str, Dict[str, float]]
    polymarket_sentiment: float
    polymarket_last_fetch: Optional[datetime] = None


@dataclass
class AgentState:
    """Operational state of the trading agent."""

    state: str  # "RUNNING", "STOPPED", "HALTED"
    initial_portfolio_value: Optional[float]
    start_time: datetime
    last_heartbeat: datetime
    crash_count: int = 0
